### ISSUE TITLE
Buttons do not have focused accent

### ISSUE THREAD

**Issue by hlibkoval** [dicolar/jbootx#2]
Tabbing through buttons is impossible because focused buttons don't have any accents. It's impossible to tell which button is focused at the moment.

**Comment by dicolar** [comment]
uh...do you mean the OUTLINE for the widget?

**Comment by hlibkoval** [comment]
Yeah, right, outline. It's missing for the buttons and it's quite bad for UX

**Comment by dicolar** [comment]
added!
